name: Regular health check

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-oz9x.onrender.com/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 10s
          retry-all: true
      - name: Notify if service is down
        uses: sarisia/actions-status-discord@v1.15.1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: ALERT! Health check failed!
          description: The service is down, please check it! 💀
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub Actions Bot
          color: 0xFF0000
      - name: Heath Check Pass
        uses: sarisia/actions-status-discord@v1.15.1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: Health Check Passed.
          description: Health Check passed and everything seems to be OK ✅
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub Actions Bot
          color: 0x3bb143
