name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30                   
      - name: Test Success 
          uses: rjstone/discord-webhook-notify@v1.0.4
          if: ${{ success() }}
          with:
            severity: info
            avatarUrl: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHubActions
            text: A new version of Pokedex deployed.
            description: Tests and Deployment Succeeded!
            details: https://full-stack-open-pokedex-oz9x.onrender.com by ${{ github.actor }} ✅
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure 
          uses: rjstone/discord-webhook-notify@v1.0.4
          if: ${{ failure() }}
          with:
            severity: error
            avatarUrl: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHubActions
            text: Build Failed!.
            description: Tests and Deployment Failed!
            details: Commit [${{ github.event.head_commit.id }}](https://github.com/${{ github.repository }}/commit/${{ github.event.head_commit.id }}) by ${{ github.actor }} broke the build! ❌
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deploy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        env:
          deploy_url: https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        run: |
          curl "$deploy_url"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
